import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import { useEffect } from "react";
import { Navbar } from "@/components/site/Navbar";
import { Footer } from "@/components/site/Footer";

export default function Privacy() {
  useEffect(() => { document.title = "Privacy Policy — QR Forge"; }, []);
  return (
    <div className="min-h-screen">
      <Navbar />
      <main className="container max-w-3xl py-12">
        <Link
          to="/"
          className="mb-6 inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-primary"
        >
          <ArrowLeft className="h-4 w-4" /> Back to QR Forge
        </Link>

        <article className="surface-card p-8 sm:p-10 prose-content">
          <h1 className="text-3xl font-bold tracking-tight">Privacy Policy</h1>
          <p className="mt-2 text-sm text-muted-foreground">Last updated: May 28, 2026</p>

          <p className="mt-6">
            Welcome to QR Forge (“we,” “our,” or “us”). This Privacy Policy explains how we collect, use, disclose, and safeguard your information when you visit our website <a href="https://onlineqrcodegenerator.lovable.app/" className="text-primary hover:underline" target="_blank" rel="noreferrer">https://onlineqrcodegenerator.lovable.app/</a> (the “Service”).
          </p>

          <p className="mt-4">
            By accessing or using our Service, you agree to the collection and use of information in accordance with this Privacy Policy.
          </p>

          <Section title="1. Interpretation and Definitions">
            <p><strong>Interpretation</strong></p>
            <p>
              Words with capitalized initial letters have meanings defined under the following conditions. These definitions shall apply regardless of whether they appear in singular or plural.
            </p>
            <p className="mt-3"><strong>Definitions</strong></p>
            <ul className="list-disc space-y-2 pl-5">
              <li><strong>Account</strong> means a unique account created for you to access our Service or parts of our Service.</li>
              <li><strong>Company</strong> (referred to as “the Company”, “we”, “us” or “our” in this Agreement) refers to QR Forge.</li>
              <li><strong>Country</strong> refers to Ethiopia.</li>
              <li><strong>Cookies</strong> are small files placed on your device by a website that contain details of your browsing history and other information.</li>
              <li><strong>Device</strong> means any device that can access the Service such as a computer, cellphone, or tablet.</li>
              <li><strong>Personal Data</strong> means any information that relates to an identified or identifiable individual.</li>
              <li><strong>Service</strong> refers to the website QR Forge.</li>
              <li><strong>Service Provider</strong> means any natural or legal person who processes data on behalf of the Company.</li>
              <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
              <li><strong>You</strong> means the individual accessing or using the Service.</li>
            </ul>
          </Section>

          <Section title="2. Information We Collect">
            <p>
              We may collect several different types of information for various purposes to provide and improve our Service.
            </p>
            <p className="mt-3"><strong>Personal Data</strong></p>
            <p>
              While using our Service, we may ask you to provide certain personally identifiable information, including but not limited to:
            </p>
            <ul className="list-disc space-y-2 pl-5">
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Phone number</li>
              <li>Address, State, Province, ZIP/Postal code, City</li>
              <li>Any other information voluntarily submitted through forms or communication channels</li>
            </ul>
            <p className="mt-3"><strong>Usage Data</strong></p>
            <p>Usage Data may include information such as:</p>
            <ul className="list-disc space-y-2 pl-5">
              <li>Your device’s Internet Protocol address (IP address)</li>
              <li>Browser type and version</li>
              <li>Pages visited on our Service</li>
              <li>Time and date of your visit</li>
              <li>Time spent on pages</li>
              <li>Unique device identifiers</li>
              <li>Diagnostic data</li>
            </ul>
            <p className="mt-3"><strong>Tracking Technologies and Cookies</strong></p>
            <p>
              We use Cookies and similar tracking technologies to track activity on our Service and store certain information.
            </p>
            <p className="mt-2">Technologies we use may include:</p>
            <ul className="list-disc space-y-2 pl-5">
              <li>Cookies or Browser Cookies</li>
              <li>Web beacons</li>
              <li>Tracking pixels</li>
              <li>Scripts</li>
            </ul>
            <p className="mt-2">
              You can instruct your browser to refuse all Cookies or indicate when a Cookie is being sent. However, some parts of the Service may not function properly without Cookies.
            </p>
          </Section>

          <Section title="3. Analytics">
            <p>
              We may use third-party Service Providers to monitor and analyze the use of our Service.
            </p>
            <p className="mt-3"><strong>Google Analytics</strong></p>
            <p>
              Google Analytics is a web analytics service provided by Google that tracks and reports website traffic.
            </p>
            <p>
              Google may use the collected data to contextualize and personalize ads within its own advertising network.
            </p>
            <p>
              You can opt out of Google Analytics by installing the Google Analytics opt-out browser add-on.
            </p>
            <p>
              For more information, visit: <a href="https://policies.google.com/privacy" className="text-primary hover:underline" target="_blank" rel="noreferrer">https://policies.google.com/privacy</a>
            </p>
            <p className="mt-3"><strong>Firebase</strong></p>
            <p>
              Firebase is provided by Google Inc. and may collect information regarding app performance, analytics, and usage behavior.
            </p>
            <p>
              For more information: <a href="https://firebase.google.com/support/privacy" className="text-primary hover:underline" target="_blank" rel="noreferrer">https://firebase.google.com/support/privacy</a>
            </p>
          </Section>

          <Section title="4. How We Use Your Information">
            <p>We may use Personal Data for the following purposes:</p>
            <ul className="list-disc space-y-2 pl-5">
              <li>To provide and maintain our Service</li>
              <li>To manage user accounts</li>
              <li>To communicate with users</li>
              <li>To send updates, marketing emails, and promotional content</li>
              <li>To improve website functionality and user experience</li>
              <li>To monitor the usage of our Service</li>
              <li>To detect, prevent, and address technical issues</li>
              <li>To personalize content and advertising</li>
              <li>To comply with legal obligations</li>
            </ul>
          </Section>

          <Section title="5. Email Communications">
            <p>
              We may use your Personal Data to contact you with newsletters, promotional materials, updates, and other information that may be of interest to you.
            </p>
            <p>
              You may opt out of receiving marketing communications at any time by clicking the unsubscribe link or contacting us directly.
            </p>
          </Section>

          <Section title="6. Advertising">
            <p>
              We display advertisements on our website using third-party advertising services, including:
            </p>
            <p className="mt-2"><strong>Google AdSense</strong></p>
            <p>
              Google AdSense uses Cookies to serve ads based on a user's previous visits to our website or other websites.
            </p>
            <p>
              Google’s use of advertising Cookies enables it and its partners to serve ads based on user visits to our Service and/or other websites on the Internet.
            </p>
            <p>
              Users may opt out of personalized advertising by visiting: <a href="https://www.google.com/settings/ads" className="text-primary hover:underline" target="_blank" rel="noreferrer">https://www.google.com/settings/ads</a>
            </p>
          </Section>

          <Section title="7. Remarketing">
            <p>
              We may use remarketing services to advertise to you after you visited our Service.
            </p>
            <p>
              Third-party vendors may use Cookies to inform, optimize, and serve ads based on your past visits to our Service.
            </p>
          </Section>

          <Section title="8. reCAPTCHA">
            <p>
              We may use Google Invisible reCAPTCHA to protect our website from spam and abuse.
            </p>
            <p>
              The use of reCAPTCHA is subject to Google’s Privacy Policy and Terms of Service.
            </p>
            <ul className="list-disc space-y-2 pl-5">
              <li>Privacy Policy: <a href="https://policies.google.com/privacy" className="text-primary hover:underline" target="_blank" rel="noreferrer">https://policies.google.com/privacy</a></li>
              <li>Terms: <a href="https://policies.google.com/terms" className="text-primary hover:underline" target="_blank" rel="noreferrer">https://policies.google.com/terms</a></li>
            </ul>
          </Section>

          <Section title="9. Payments">
            <p>
              We may provide paid products and/or services within the Service.
            </p>
            <p>
              In that case, we may use third-party payment processors to process payments securely.
            </p>
            <p>
              We do not store or collect your payment card details directly. That information is provided directly to third-party payment processors whose use of your personal information is governed by their Privacy Policy.
            </p>
          </Section>

          <Section title="10. Retention of Data">
            <p>
              We will retain your Personal Data only for as long as necessary for the purposes set out in this Privacy Policy.
            </p>
            <p>
              We may retain Usage Data for internal analysis purposes, security improvements, legal obligations, and compliance requirements.
            </p>
          </Section>

          <Section title="11. Transfer of Data">
            <p>
              Your information, including Personal Data, may be transferred to and maintained on computers located outside your jurisdiction where data protection laws may differ.
            </p>
            <p>
              By using our Service and submitting information, you consent to this transfer.
            </p>
          </Section>

          <Section title="12. Disclosure of Data">
            <p>We may disclose your Personal Data:</p>
            <ul className="list-disc space-y-2 pl-5">
              <li>To comply with legal obligations</li>
              <li>To protect and defend our rights or property</li>
              <li>To prevent or investigate wrongdoing</li>
              <li>To protect the personal safety of users or the public</li>
              <li>To protect against legal liability</li>
            </ul>
          </Section>

          <Section title="13. Security of Data">
            <p>
              We value your trust in providing us your Personal Data. However, no method of transmission over the Internet or electronic storage is 100% secure.
            </p>
            <p>
              While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.
            </p>
          </Section>

          <Section title="14. GDPR Privacy Rights">
            <p>
              If you are from the European Economic Area (EEA), you have certain data protection rights under the GDPR.
            </p>
            <p>These rights may include:</p>
            <ul className="list-disc space-y-2 pl-5">
              <li>The right to access</li>
              <li>The right to rectification</li>
              <li>The right to erasure</li>
              <li>The right to restrict processing</li>
              <li>The right to object to processing</li>
              <li>The right to data portability</li>
            </ul>
            <p className="mt-2">To exercise any of these rights, please contact us.</p>
          </Section>

          <Section title="15. CCPA/CPRA Privacy Rights">
            <p>
              If you are a California resident, you have rights under the California Consumer Privacy Act (CCPA) and California Privacy Rights Act (CPRA), including:
            </p>
            <ul className="list-disc space-y-2 pl-5">
              <li>The right to know what personal information is collected</li>
              <li>The right to request deletion of personal information</li>
              <li>The right to correct inaccurate information</li>
              <li>The right to opt out of the sale or sharing of personal data</li>
              <li>The right to non-discrimination for exercising privacy rights</li>
            </ul>
            <p className="mt-2">We do not knowingly sell personal information.</p>
          </Section>

          <Section title="16. CalOPPA Compliance">
            <p>In accordance with the California Online Privacy Protection Act (CalOPPA):</p>
            <ul className="list-disc space-y-2 pl-5">
              <li>Users can visit our site anonymously</li>
              <li>Our Privacy Policy link includes the word “Privacy”</li>
              <li>Users will be notified of Privacy Policy changes on this page</li>
            </ul>
          </Section>

          <Section title="17. Children’s Privacy">
            <p>Our Service is not directed to anyone under the age of 13.</p>
            <p>We do not knowingly collect personally identifiable information from children under 13.</p>
            <p>If you believe a child has provided us with Personal Data, please contact us immediately.</p>
          </Section>

          <Section title="18. Third-Party Links">
            <p>
              Our Service may contain links to third-party websites that are not operated by us.
            </p>
            <p>
              We strongly advise you to review the Privacy Policy of every site you visit.
            </p>
            <p>
              We assume no responsibility for the content, privacy policies, or practices of third-party websites or services.
            </p>
          </Section>

          <Section title="19. Changes to This Privacy Policy">
            <p>
              We may update our Privacy Policy from time to time.
            </p>
            <p>
              Changes will be posted on this page with an updated revision date.
            </p>
            <p>
              You are advised to review this Privacy Policy periodically for any changes.
            </p>
          </Section>

          <Section title="20. Contact Us">
            <p>
              If you have any questions about this Privacy Policy, please reach out via our contact page:
            </p>
            <ul className="list-disc space-y-2 pl-5">
              <li>
                <Link to="/contact" className="text-primary hover:underline">
                  Visit our Contact page
                </Link>
              </li>
            </ul>
          </Section>

        </article>
      </main>
      <Footer />
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mt-8">
      <h2 className="text-lg font-semibold">{title}</h2>
      <div className="mt-2 space-y-3 text-sm leading-relaxed text-muted-foreground">
        {children}
      </div>
    </section>
  );
}